updated doc format for Running ASTRA-sim
astra-sim/astra-sim.github.io pull request #5
Opened 2023-10-18 19:07 UTC by zli669

2023-10-19 22:16 UTC, willjwon requested changes

2023-10-19 22:16 UTC, willjwon commented on pages/docs/Argument ${NETWORK_CONFIG}.rst
> +Argument ${NETWORK_CONFIG}
All updates looks good to me, but can you please change the filenames of those `rst` to not have any special characters or spaces? These filename seems irregular and might look awkward when appeared in URLs.

Something like `network_config_arguments.rst` or whatnot.

2023-10-22 18:03 UTC, zli669 reviewed
@willjwon Hi Will, thank you for the comments. I have updated the file names to avoid spaces and special characters. Please review. Thanks again!

2023-10-23 17:38 UTC, willjwon approved these changes

2023-10-23 17:38 UTC, willjwon commented
@zli669 Approved, thanks!

2023-10-24 08:10 UTC, willjwon commented
Closing this PR, please migrate the contents to this repo: https://github.com/astra-sim/astra-sim-docs

2023-10-24 08:10 UTC, closed without merging